# Generated by Django 4.2.2 on 2023-07-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentsProfile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agentshift',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
