# Generated by Django 4.2.1 on 2023-07-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
